"""Tambah kolom dcanceled_at ke tabel booking

Revision ID: 0753e15a5caa
Revises: 940b6aa33320
Create Date: 2025-11-12 13:14:14.577388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0753e15a5caa'
down_revision: Union[str, Sequence[str], None] = '940b6aa33320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_tblm_permissions_vcode'), table_name='tblm_permissions')
    # op.drop_index(op.f('uq_permission_vcode_vname'), table_name='tblm_permissions')
    # op.drop_table('tblm_permissions')
    # op.drop_index(op.f('ix_tblr_role_permissions_vcode'), table_name='tblr_role_permissions')
    # op.drop_index(op.f('uq_role_permission_combination'), table_name='tblr_role_permissions')
    # op.drop_table('tblr_role_permissions')
    op.add_column('tblt_booking', sa.Column('dcanceled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblt_booking', 'dcanceled_at')
    # op.create_table('tblr_role_permissions',
    # sa.Column('nid', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('vcode', mysql.VARCHAR(length=100), nullable=False),
    # sa.Column('nid_role', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('nid_permission', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('nstatus', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('dcreated_at', mysql.DATETIME(), nullable=True),
    # sa.Column('vcreated_by', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('dmodified_at', mysql.DATETIME(), nullable=True),
    # sa.Column('vmodified_by', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('dsort_at', mysql.DATETIME(), nullable=True),
    # sa.CheckConstraint('(`nstatus` in (0,1))', name=op.f('chk_role_permissions_nstatus_values')),
    # sa.ForeignKeyConstraint(['nid_permission'], ['tblm_permissions.nid'], name=op.f('tblr_role_permissions_ibfk_2')),
    # sa.ForeignKeyConstraint(['nid_role'], ['tblm_roles.nid'], name=op.f('tblr_role_permissions_ibfk_1')),
    # sa.PrimaryKeyConstraint('nid'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index(op.f('uq_role_permission_combination'), 'tblr_role_permissions', ['nid_role', 'nid_permission'], unique=True)
    # op.create_index(op.f('ix_tblr_role_permissions_vcode'), 'tblr_role_permissions', ['vcode'], unique=True)
    # op.create_table('tblm_permissions',
    # sa.Column('nid', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('vcode', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('vname', mysql.VARCHAR(length=255), nullable=False),
    # sa.Column('vdesc', mysql.TEXT(), nullable=False),
    # sa.Column('nstatus', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('dcreated_at', mysql.DATETIME(), nullable=True),
    # sa.Column('vcreated_by', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('dmodified_at', mysql.DATETIME(), nullable=True),
    # sa.Column('vmodified_by', mysql.VARCHAR(length=100), nullable=True),
    # sa.Column('dsort_at', mysql.DATETIME(), nullable=True),
    # sa.CheckConstraint('(`nstatus` in (0,1))', name=op.f('chk_permissions_nstatus_values')),
    # sa.PrimaryKeyConstraint('nid'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index(op.f('uq_permission_vcode_vname'), 'tblm_permissions', ['vcode', 'vname'], unique=True)
    # op.create_index(op.f('ix_tblm_permissions_vcode'), 'tblm_permissions', ['vcode'], unique=True)
    # ### end Alembic commands ###
