"""add lab gallery and hero image

Revision ID: 4652d562ecb6
Revises: e14c3f3a8507
Create Date: 2025-11-22 21:48:53.689349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4652d562ecb6'
down_revision: Union[str, Sequence[str], None] = 'e14c3f3a8507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblm_lab', sa.Column('hero_image_vcode', sa.String(length=100), nullable=True))
    # op.alter_column('tblr_lab_content_files', 'vcode_lab_content',
    #            existing_type=mysql.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    op.add_column('tblt_booking', sa.Column('dcanceled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblt_booking', 'dcanceled_at')
    # op.alter_column('tblr_lab_content_files', 'vcode_lab_content',
    #            existing_type=sa.String(length=100),
    #            type_=mysql.TEXT(),
    #            nullable=True)
    op.drop_column('tblm_lab', 'hero_image_vcode')
    # ### end Alembic commands ###
