"""'init'

Revision ID: 524b4f675aa1
Revises: 
Create Date: 2025-10-30 22:15:43.578041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524b4f675aa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblm_department',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_department_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_departmment_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_department_vcode'), 'tblm_department', ['vcode'], unique=True)
    op.create_table('tblm_files',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vtype', sa.Text(), nullable=False),
    sa.Column('vpath', sa.Text(), nullable=False),
    sa.Column('vextension', sa.String(length=100), nullable=False),
    sa.Column('nsize', sa.Float(), nullable=False),
    sa.Column('vcategory', sa.String(length=100), nullable=False),
    sa.Column('nis_public', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nis_public IN (0, 1)', name='chk_files_nis_public_values'),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_files_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_files_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_files_vcode'), 'tblm_files', ['vcode'], unique=True)
    op.create_table('tblm_lab',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('ncapacity', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_lab_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_lab_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_lab_vcode'), 'tblm_lab', ['vcode'], unique=True)
    op.create_table('tblm_roles',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_roles_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_roles_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_roles_vcode'), 'tblm_roles', ['vcode'], unique=True)
    op.create_table('tbls_users',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vphone', sa.String(length=20), nullable=True),
    sa.Column('vemail', sa.String(length=255), nullable=False),
    sa.Column('vaddress', sa.Text(), nullable=True),
    sa.Column('vpassword', sa.String(length=255), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status User: 0=Inactive, 1=Active, 2=Pending, 3=Expired'),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1, 2, 3)', name='chk_users_nstatus_values'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_users_vcode'), 'tbls_users', ['vcode'], unique=True)
    op.create_index(op.f('ix_tbls_users_vemail'), 'tbls_users', ['vemail'], unique=True)
    op.create_table('tblm_facility',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_facilities_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_facilities_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_facility_vcode'), 'tblm_facility', ['vcode'], unique=True)
    op.create_table('tblr_department_lab',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_department', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_department_lab_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_department'], ['tblm_department.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_lab', 'nid_department', name='u_department_lab_combination')
    )
    op.create_index(op.f('ix_tblr_department_lab_vcode'), 'tblr_department_lab', ['vcode'], unique=True)
    op.create_table('tblr_user_access',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('nid_role', sa.Integer(), nullable=False),
    sa.Column('nid_department', sa.Integer(), nullable=True),
    sa.Column('nid_lab', sa.Integer(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_user_access_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_department'], ['tblm_department.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.ForeignKeyConstraint(['nid_role'], ['tblm_roles.nid'], ),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_user', 'nid_role', 'nid_department', 'nid_lab', name='uq_user_access_combination')
    )
    op.create_index(op.f('ix_tblr_user_access_vcode'), 'tblr_user_access', ['vcode'], unique=True)
    op.create_table('tbls_token',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False, comment='Foreign key ke tabel user (tbls_users)'),
    sa.Column('ntoken_type', sa.Integer(), nullable=False, comment='Tipe token: 1=Aktivasi, 2=Sesi Login, 3=Reset Password, 4=Ganti Email'),
    sa.Column('vcode', sa.String(length=255), nullable=False, comment='Kode unik untuk token aktivasi atau password reset'),
    sa.Column('vnew_email', sa.String(length=255), nullable=True, comment='Email baru yang menunggu verifikasi'),
    sa.Column('vaccess_token', sa.Text(), nullable=True, comment='JWT access token untuk sesi login'),
    sa.Column('vrefresh_token', sa.Text(), nullable=True, comment='JWT refresh token untuk memperbarui access token'),
    sa.Column('vbrowser_info', sa.Text(), nullable=True, comment='Informasi browser/User-Agent dari user'),
    sa.Column('vip_address', sa.String(length=50), nullable=True, comment='Alamat IP user saat request token'),
    sa.Column('dexpires_at', sa.DateTime(timezone=True), nullable=False, comment='Waktu kedaluwarsa untuk token aktivasi atau access token'),
    sa.Column('drefresh_expire_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu kedaluwarsa untuk refresh token'),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status token: 1=Aktif, 0=Tidak Aktif/Sudah digunakan'),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_token_nstatus_values'),
    sa.CheckConstraint('ntoken_type IN (1, 2, 3, 4)', name='chk_token_type_values'),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_token_ntoken_type'), 'tbls_token', ['ntoken_type'], unique=False)
    op.create_index(op.f('ix_tbls_token_vcode'), 'tbls_token', ['vcode'], unique=True)
    op.create_table('tblr_lab_facility',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_facility', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_facility_lab_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_facility'], ['tblm_facility.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_lab', 'nid_facility', name='u_facility_lab_combination')
    )
    op.create_index(op.f('ix_tblr_lab_facility_vcode'), 'tblr_lab_facility', ['vcode'], unique=True)
    op.create_table('tblt_booking',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab_facility', sa.Integer(), nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('dstart', sa.DateTime(), nullable=False),
    sa.Column('dend', sa.DateTime(), nullable=False),
    sa.Column('vactivity', sa.Text(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=True, comment='0:Rejected, 1:Approved, 2:Pending, 3:Canceled, 4:WaitingForDoc, 5:Done'),
    sa.Column('dapproved_at', sa.DateTime(), nullable=True),
    sa.Column('vapproved_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nid_lab_facility'], ['tblr_lab_facility.nid'], ),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblt_booking_nid'), 'tblt_booking', ['nid'], unique=False)
    op.create_index(op.f('ix_tblt_booking_vcode'), 'tblt_booking', ['vcode'], unique=True)
    op.create_table('tblr_booking_files',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_booking', sa.Integer(), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('vtype', sa.String(length=50), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nid_booking'], ['tblt_booking.nid'], ),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblr_booking_files_vcode'), 'tblr_booking_files', ['vcode'], unique=True)
    op.create_index(op.f('ix_tblr_booking_files_vtype'), 'tblr_booking_files', ['vtype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblr_booking_files_vtype'), table_name='tblr_booking_files')
    op.drop_index(op.f('ix_tblr_booking_files_vcode'), table_name='tblr_booking_files')
    op.drop_table('tblr_booking_files')
    op.drop_index(op.f('ix_tblt_booking_vcode'), table_name='tblt_booking')
    op.drop_index(op.f('ix_tblt_booking_nid'), table_name='tblt_booking')
    op.drop_table('tblt_booking')
    op.drop_index(op.f('ix_tblr_lab_facility_vcode'), table_name='tblr_lab_facility')
    op.drop_table('tblr_lab_facility')
    op.drop_index(op.f('ix_tbls_token_vcode'), table_name='tbls_token')
    op.drop_index(op.f('ix_tbls_token_ntoken_type'), table_name='tbls_token')
    op.drop_table('tbls_token')
    op.drop_index(op.f('ix_tblr_user_access_vcode'), table_name='tblr_user_access')
    op.drop_table('tblr_user_access')
    op.drop_index(op.f('ix_tblr_department_lab_vcode'), table_name='tblr_department_lab')
    op.drop_table('tblr_department_lab')
    op.drop_index(op.f('ix_tblm_facility_vcode'), table_name='tblm_facility')
    op.drop_table('tblm_facility')
    op.drop_index(op.f('ix_tbls_users_vemail'), table_name='tbls_users')
    op.drop_index(op.f('ix_tbls_users_vcode'), table_name='tbls_users')
    op.drop_table('tbls_users')
    op.drop_index(op.f('ix_tblm_roles_vcode'), table_name='tblm_roles')
    op.drop_table('tblm_roles')
    op.drop_index(op.f('ix_tblm_lab_vcode'), table_name='tblm_lab')
    op.drop_table('tblm_lab')
    op.drop_index(op.f('ix_tblm_files_vcode'), table_name='tblm_files')
    op.drop_table('tblm_files')
    op.drop_index(op.f('ix_tblm_department_vcode'), table_name='tblm_department')
    op.drop_table('tblm_department')
    # ### end Alembic commands ###
