"""Replace vthumbnail with nid_file in lab_article

Revision ID: 649ab384c26a
Revises: 7a7953b92e84
Create Date: 2025-12-06 22:51:37.827214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '649ab384c26a'
down_revision: Union[str, Sequence[str], None] = '7a7953b92e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblt_lab_article', sa.Column('nid_file', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tblt_lab_article', 'tblm_files', ['nid_file'], ['nid'])
    op.drop_column('tblt_lab_article', 'vthumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblt_lab_article', sa.Column('vthumbnail', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'tblt_lab_article', type_='foreignkey')
    op.drop_column('tblt_lab_article', 'nid_file')
    # ### end Alembic commands ###
