"""add kb chatbot

Revision ID: 64a94044308c
Revises: 
Create Date: 2025-12-04 21:01:01.702610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a94044308c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblm_knowledge_base',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcategory', sa.String(length=255), nullable=True),
    sa.Column('vcontext', sa.Text(), nullable=True),
    sa.Column('vanswer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblm_knowledge_base')
    # ### end Alembic commands ###
