"""add new nstatus field to kb

Revision ID: 684668406e55
Revises: 64a94044308c
Create Date: 2025-12-04 23:41:48.545949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684668406e55'
down_revision: Union[str, Sequence[str], None] = '64a94044308c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblm_knowledge_base', sa.Column('nstatus', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblm_knowledge_base', 'nstatus')
    # ### end Alembic commands ###
