"""Initial migration, create all tables

Revision ID: 705af1930100
Revises: 
Create Date: 2025-10-14 13:48:24.020157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705af1930100'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblm_permissions',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_permissions_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_permission_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_permissions_vcode'), 'tblm_permissions', ['vcode'], unique=True)
    op.create_table('tblm_roles',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_roles_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_roles_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_roles_vcode'), 'tblm_roles', ['vcode'], unique=True)
    op.create_table('tbls_users',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vphone', sa.String(length=20), nullable=True),
    sa.Column('vemail', sa.String(length=255), nullable=False),
    sa.Column('vaddress', sa.Text(), nullable=True),
    sa.Column('vpassword', sa.String(length=255), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status User: 0=Inactive, 1=Active, 2=Pending, 3=Expired'),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1, 2, 3)', name='chk_users_nstatus_values'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_users_vcode'), 'tbls_users', ['vcode'], unique=True)
    op.create_index(op.f('ix_tbls_users_vemail'), 'tbls_users', ['vemail'], unique=True)
    op.create_table('tblr_role_permissions',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_role', sa.Integer(), nullable=False),
    sa.Column('nid_permission', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_role_permissions_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_permission'], ['tblm_permissions.nid'], ),
    sa.ForeignKeyConstraint(['nid_role'], ['tblm_roles.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_role', 'nid_permission', name='uq_role_permission_combination')
    )
    op.create_index(op.f('ix_tblr_role_permissions_vcode'), 'tblr_role_permissions', ['vcode'], unique=True)
    op.create_table('tbls_token',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False, comment='Foreign key ke tabel user (tbls_users)'),
    sa.Column('ntoken_type', sa.Integer(), nullable=False, comment='Tipe token: 1=Aktivasi, 2=Sesi Login, 3=Reset Password, 4=Ganti Email'),
    sa.Column('vcode', sa.String(length=255), nullable=False, comment='Kode unik untuk token aktivasi atau password reset'),
    sa.Column('vnew_email', sa.String(length=255), nullable=True, comment='Email baru yang menunggu verifikasi'),
    sa.Column('vaccess_token', sa.Text(), nullable=True, comment='JWT access token untuk sesi login'),
    sa.Column('vrefresh_token', sa.Text(), nullable=True, comment='JWT refresh token untuk memperbarui access token'),
    sa.Column('vbrowser_info', sa.Text(), nullable=True, comment='Informasi browser/User-Agent dari user'),
    sa.Column('vip_address', sa.String(length=50), nullable=True, comment='Alamat IP user saat request token'),
    sa.Column('dexpires_at', sa.DateTime(timezone=True), nullable=False, comment='Waktu kedaluwarsa untuk token aktivasi atau access token'),
    sa.Column('drefresh_expire_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu kedaluwarsa untuk refresh token'),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status token: 1=Aktif, 0=Tidak Aktif/Sudah digunakan'),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_token_nstatus_values'),
    sa.CheckConstraint('ntoken_type IN (1, 2, 3, 4)', name='chk_token_type_values'),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_token_ntoken_type'), 'tbls_token', ['ntoken_type'], unique=False)
    op.create_index(op.f('ix_tbls_token_vcode'), 'tbls_token', ['vcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbls_token_vcode'), table_name='tbls_token')
    op.drop_index(op.f('ix_tbls_token_ntoken_type'), table_name='tbls_token')
    op.drop_table('tbls_token')
    op.drop_index(op.f('ix_tblr_role_permissions_vcode'), table_name='tblr_role_permissions')
    op.drop_table('tblr_role_permissions')
    op.drop_index(op.f('ix_tbls_users_vemail'), table_name='tbls_users')
    op.drop_index(op.f('ix_tbls_users_vcode'), table_name='tbls_users')
    op.drop_table('tbls_users')
    op.drop_index(op.f('ix_tblm_roles_vcode'), table_name='tblm_roles')
    op.drop_table('tblm_roles')
    op.drop_index(op.f('ix_tblm_permissions_vcode'), table_name='tblm_permissions')
    op.drop_table('tblm_permissions')
    # ### end Alembic commands ###
