"""Add LabArticle and ArticleTag tables

Revision ID: 7a7953b92e84
Revises: 7302794ca5d6
Create Date: 2025-12-06 16:53:52.967707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7953b92e84'
down_revision: Union[str, Sequence[str], None] = '7302794ca5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblt_lab_article',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('vtitle', sa.String(length=255), nullable=False),
    sa.Column('vexcerpt', sa.Text(), nullable=True),
    sa.Column('vcontent', sa.Text(), nullable=False),
    sa.Column('vthumbnail', sa.String(length=500), nullable=True),
    sa.Column('nis_featured', sa.Integer(), nullable=True, comment='0:No, 1:Yes'),
    sa.Column('nstatus', sa.Integer(), nullable=True, comment='0:Inactive, 1:Published, 2:Scheduled'),
    sa.Column('dpublished_at', sa.DateTime(), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nis_featured IN (0, 1)', name='article_nis_featured_check'),
    sa.CheckConstraint('nstatus IN (0, 1, 2)', name='article_nstatus_check'),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblt_lab_article_nid'), 'tblt_lab_article', ['nid'], unique=False)
    op.create_index(op.f('ix_tblt_lab_article_vcode'), 'tblt_lab_article', ['vcode'], unique=True)
    op.create_table('tblr_article_tag',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_article', sa.Integer(), nullable=False),
    sa.Column('vtag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nid_article'], ['tblt_lab_article.nid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblr_article_tag_nid'), 'tblr_article_tag', ['nid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblr_article_tag_nid'), table_name='tblr_article_tag')
    op.drop_table('tblr_article_tag')
    op.drop_index(op.f('ix_tblt_lab_article_vcode'), table_name='tblt_lab_article')
    op.drop_index(op.f('ix_tblt_lab_article_nid'), table_name='tblt_lab_article')
    op.drop_table('tblt_lab_article')
    # ### end Alembic commands ###
