"""Create tblm_roles

Revision ID: 9725adfef4c8
Revises: 
Create Date: 2025-10-02 16:02:29.207673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9725adfef4c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblm_roles',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=255), nullable=False),
    sa.Column('vmodified_by', sa.String(length=255), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_nstatus_values'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblm_roles_vcode'), 'tblm_roles', ['vcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblm_roles_vcode'), table_name='tblm_roles')
    op.drop_table('tblm_roles')
    # ### end Alembic commands ###
