"""add new field audit

Revision ID: b8f77d4490d2
Revises: 684668406e55
Create Date: 2025-12-04 23:55:00.437489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f77d4490d2'
down_revision: Union[str, Sequence[str], None] = '684668406e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblm_knowledge_base', sa.Column('dcreated_at', sa.DateTime(), nullable=True))
    op.add_column('tblm_knowledge_base', sa.Column('vcreated_by', sa.String(length=100), nullable=True))
    op.add_column('tblm_knowledge_base', sa.Column('dmodified_at', sa.DateTime(), nullable=True))
    op.add_column('tblm_knowledge_base', sa.Column('vmodified_by', sa.String(length=100), nullable=True))
    op.add_column('tblm_knowledge_base', sa.Column('dsort_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblm_knowledge_base', 'dsort_at')
    op.drop_column('tblm_knowledge_base', 'vmodified_by')
    op.drop_column('tblm_knowledge_base', 'dmodified_at')
    op.drop_column('tblm_knowledge_base', 'vcreated_by')
    op.drop_column('tblm_knowledge_base', 'dcreated_at')
    # ### end Alembic commands ###
