"""init

Revision ID: ef74d88de038
Revises: 
Create Date: 2025-12-04 13:52:28.837334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef74d88de038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblm_building',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_building_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_building_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_building_vcode'), 'tblm_building', ['vcode'], unique=True)
    op.create_table('tblm_department',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_department_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_departmment_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_department_vcode'), 'tblm_department', ['vcode'], unique=True)
    op.create_table('tblm_files',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vtype', sa.Text(), nullable=False),
    sa.Column('vpath', sa.Text(), nullable=False),
    sa.Column('vextension', sa.String(length=100), nullable=False),
    sa.Column('nsize', sa.Float(), nullable=False),
    sa.Column('vcategory', sa.String(length=100), nullable=False),
    sa.Column('nis_public', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nis_public IN (0, 1)', name='chk_files_nis_public_values'),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_files_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_files_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_files_vcode'), 'tblm_files', ['vcode'], unique=True)
    op.create_table('tblm_permissions',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_permissions_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_permission_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_permissions_vcode'), 'tblm_permissions', ['vcode'], unique=True)
    op.create_table('tblm_roles',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_roles_nstatus_values'),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_roles_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_roles_vcode'), 'tblm_roles', ['vcode'], unique=True)
    op.create_table('tbls_users',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vphone', sa.String(length=20), nullable=True),
    sa.Column('vemail', sa.String(length=255), nullable=False),
    sa.Column('vaddress', sa.Text(), nullable=True),
    sa.Column('vpassword', sa.String(length=255), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status User: 0=Inactive, 1=Active, 2=Pending, 3=Expired'),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1, 2, 3)', name='chk_users_nstatus_values'),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_users_vcode'), 'tbls_users', ['vcode'], unique=True)
    op.create_index(op.f('ix_tbls_users_vemail'), 'tbls_users', ['vemail'], unique=True)
    op.create_table('tblh_activity_logs',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('vaction', sa.String(length=50), nullable=False),
    sa.Column('vtarget_model', sa.String(length=100), nullable=False),
    sa.Column('vtarget_identifier', sa.String(length=255), nullable=False),
    sa.Column('jbefore', sa.JSON(), nullable=True),
    sa.Column('jafter', sa.JSON(), nullable=True),
    sa.Column('dtimestamp', sa.DateTime(), nullable=True),
    sa.Column('vip_address', sa.String(length=100), nullable=True),
    sa.Column('vuser_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblh_activity_logs_dtimestamp'), 'tblh_activity_logs', ['dtimestamp'], unique=False)
    op.create_index(op.f('ix_tblh_activity_logs_nid_user'), 'tblh_activity_logs', ['nid_user'], unique=False)
    op.create_index(op.f('ix_tblh_activity_logs_vaction'), 'tblh_activity_logs', ['vaction'], unique=False)
    op.create_index(op.f('ix_tblh_activity_logs_vtarget_identifier'), 'tblh_activity_logs', ['vtarget_identifier'], unique=False)
    op.create_index(op.f('ix_tblh_activity_logs_vtarget_model'), 'tblh_activity_logs', ['vtarget_model'], unique=False)
    op.create_table('tblh_security_logs',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=True),
    sa.Column('vaction', sa.String(length=100), nullable=False),
    sa.Column('vip_address', sa.String(length=100), nullable=True),
    sa.Column('vuser_agent', sa.Text(), nullable=True),
    sa.Column('vdetails', sa.Text(), nullable=True),
    sa.Column('dtimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblh_security_logs_dtimestamp'), 'tblh_security_logs', ['dtimestamp'], unique=False)
    op.create_index(op.f('ix_tblh_security_logs_nid_user'), 'tblh_security_logs', ['nid_user'], unique=False)
    op.create_index(op.f('ix_tblh_security_logs_vaction'), 'tblh_security_logs', ['vaction'], unique=False)
    op.create_table('tblm_facility',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_facilities_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_facilities_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_facility_vcode'), 'tblm_facility', ['vcode'], unique=True)
    op.create_table('tblm_lab',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vname', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('ncapacity', sa.Integer(), nullable=False),
    sa.Column('nid_building', sa.Integer(), nullable=False),
    sa.Column('vroom_number', sa.String(length=100), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_lab_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_building'], ['tblm_building.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vname', name='uq_lab_vcode_vname')
    )
    op.create_index(op.f('ix_tblm_lab_vcode'), 'tblm_lab', ['vcode'], unique=True)
    op.create_table('tblr_role_permissions',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_role', sa.Integer(), nullable=False),
    sa.Column('nid_permission', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_role_permissions_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_permission'], ['tblm_permissions.nid'], ),
    sa.ForeignKeyConstraint(['nid_role'], ['tblm_roles.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_role', 'nid_permission', name='uq_role_permission_combination')
    )
    op.create_index(op.f('ix_tblr_role_permissions_vcode'), 'tblr_role_permissions', ['vcode'], unique=True)
    op.create_table('tbls_landing_page',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('vsection_name', sa.String(length=255), nullable=False),
    sa.Column('vdesc', sa.Text(), nullable=False),
    sa.Column('vtitle', sa.String(length=255), nullable=False),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('nid_image', sa.Integer(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_landing_page_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_image'], ['tblm_files.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vsection_name', name='uq_landing_page_vcode_vsection_name')
    )
    op.create_index(op.f('ix_tbls_landing_page_vcode'), 'tbls_landing_page', ['vcode'], unique=True)
    op.create_table('tbls_token',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False, comment='Foreign key ke tabel user (tbls_users)'),
    sa.Column('ntoken_type', sa.Integer(), nullable=False, comment='Tipe token: 1=Aktivasi, 2=Sesi Login, 3=Reset Password, 4=Ganti Email'),
    sa.Column('vcode', sa.String(length=255), nullable=False, comment='Kode unik untuk token aktivasi atau password reset'),
    sa.Column('vnew_email', sa.String(length=255), nullable=True, comment='Email baru yang menunggu verifikasi'),
    sa.Column('vaccess_token', sa.Text(), nullable=True, comment='JWT access token untuk sesi login'),
    sa.Column('vrefresh_token', sa.Text(), nullable=True, comment='JWT refresh token untuk memperbarui access token'),
    sa.Column('vbrowser_info', sa.Text(), nullable=True, comment='Informasi browser/User-Agent dari user'),
    sa.Column('vip_address', sa.String(length=50), nullable=True, comment='Alamat IP user saat request token'),
    sa.Column('dexpires_at', sa.DateTime(timezone=True), nullable=False, comment='Waktu kedaluwarsa untuk token aktivasi atau access token'),
    sa.Column('drefresh_expire_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu kedaluwarsa untuk refresh token'),
    sa.Column('nstatus', sa.Integer(), nullable=False, comment='Status token: 1=Aktif, 0=Tidak Aktif/Sudah digunakan'),
    sa.Column('dcreated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dmodified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_token_nstatus_values'),
    sa.CheckConstraint('ntoken_type IN (1, 2, 3, 4)', name='chk_token_type_values'),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tbls_token_ntoken_type'), 'tbls_token', ['ntoken_type'], unique=False)
    op.create_index(op.f('ix_tbls_token_vcode'), 'tbls_token', ['vcode'], unique=True)
    op.create_table('tblr_department_lab',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_department', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_department_lab_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_department'], ['tblm_department.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_lab', 'nid_department', name='u_department_lab_combination')
    )
    op.create_index(op.f('ix_tblr_department_lab_vcode'), 'tblr_department_lab', ['vcode'], unique=True)
    op.create_table('tblr_lab_content',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('vtitle', sa.String(length=255), nullable=False),
    sa.Column('vslug_url', sa.String(length=255), nullable=False),
    sa.Column('vsummary', sa.Text(), nullable=False),
    sa.Column('vcontent', sa.Text(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_lab_content_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'vtitle', name='uq_lab_content_vcode_vtitle')
    )
    op.create_index(op.f('ix_tblr_lab_content_vcode'), 'tblr_lab_content', ['vcode'], unique=True)
    op.create_table('tblr_lab_facility',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('vcode_lab', sa.String(length=100), nullable=False),
    sa.Column('vcode_facility', sa.String(length=100), nullable=False),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_facility', sa.Integer(), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_facility_lab_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_facility'], ['tblm_facility.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_lab', 'nid_facility', name='u_facility_lab_combination')
    )
    op.create_index(op.f('ix_tblr_lab_facility_vcode'), 'tblr_lab_facility', ['vcode'], unique=True)
    op.create_table('tblr_lab_gallery',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab', sa.Integer(), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('ntype', sa.Integer(), nullable=False, comment='1 = Hero Image, 2 = Gallery Image'),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_lab_gallery_nstatus_values'),
    sa.CheckConstraint('ntype IN (1, 2)', name='chk_lab_gallery_ntype_values'),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_lab', 'nid_file', name='uq_lab_gallery_lab_file')
    )
    op.create_index(op.f('ix_tblr_lab_gallery_vcode'), 'tblr_lab_gallery', ['vcode'], unique=True)
    op.create_table('tblr_user_access',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('nid_role', sa.Integer(), nullable=False),
    sa.Column('nid_department', sa.Integer(), nullable=True),
    sa.Column('nid_lab', sa.Integer(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_user_access_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_department'], ['tblm_department.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab'], ['tblm_lab.nid'], ),
    sa.ForeignKeyConstraint(['nid_role'], ['tblm_roles.nid'], ),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('nid_user', 'nid_role', 'nid_department', 'nid_lab', name='uq_user_access_combination')
    )
    op.create_index(op.f('ix_tblr_user_access_vcode'), 'tblr_user_access', ['vcode'], unique=True)
    op.create_table('tbls_landing_page_image',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('nid_landing_page_section', sa.Integer(), nullable=False),
    sa.Column('vlandingpage_image_to_landingpage_vcode', sa.String(length=100), nullable=False),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.CheckConstraint('nstatus IN (0, 1)', name='chk_landing_page_image_nstatus_values'),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.ForeignKeyConstraint(['nid_landing_page_section'], ['tbls_landing_page.nid'], ),
    sa.PrimaryKeyConstraint('nid'),
    sa.UniqueConstraint('vcode', 'nid_landing_page_section', name='uq_landing_page_image_vcode_nid_section')
    )
    op.create_index(op.f('ix_tbls_landing_page_image_vcode'), 'tbls_landing_page_image', ['vcode'], unique=True)
    op.create_table('tblr_lab_content_files',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab_content', sa.Integer(), nullable=False),
    sa.Column('vcode_lab_content', sa.String(length=100), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.ForeignKeyConstraint(['nid_lab_content'], ['tblr_lab_content.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblr_lab_content_files_vcode'), 'tblr_lab_content_files', ['vcode'], unique=True)
    op.create_table('tblt_booking',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=True),
    sa.Column('nid_lab_facility', sa.Integer(), nullable=False),
    sa.Column('nid_user', sa.Integer(), nullable=False),
    sa.Column('dstart', sa.DateTime(), nullable=False),
    sa.Column('dend', sa.DateTime(), nullable=False),
    sa.Column('vactivity', sa.Text(), nullable=True),
    sa.Column('nstatus', sa.Integer(), nullable=True, comment='0:Rejected, 1:Approved, 2:Pending, 3:Canceled, 4:WaitingForDoc, 5:Done'),
    sa.Column('nbooking_type', sa.Integer(), nullable=True, comment='0:Regular, 1:Maintenance'),
    sa.Column('dreviewed_at', sa.DateTime(), nullable=True),
    sa.Column('vreviewed_by', sa.String(length=100), nullable=True),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dcanceled_at', sa.DateTime(), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('nbooking_type IN (0, 1)', name='booking_nbooking_type_check'),
    sa.CheckConstraint('nstatus IN (0, 1, 2, 3, 4, 5)', name='booking_nstatus_check'),
    sa.ForeignKeyConstraint(['nid_lab_facility'], ['tblr_lab_facility.nid'], ),
    sa.ForeignKeyConstraint(['nid_user'], ['tbls_users.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblt_booking_nid'), 'tblt_booking', ['nid'], unique=False)
    op.create_index(op.f('ix_tblt_booking_vcode'), 'tblt_booking', ['vcode'], unique=True)
    op.create_table('tblr_booking_files',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vcode', sa.String(length=100), nullable=False),
    sa.Column('nid_booking', sa.Integer(), nullable=False),
    sa.Column('nid_file', sa.Integer(), nullable=False),
    sa.Column('vtype', sa.String(length=50), nullable=False),
    sa.Column('nstatus', sa.Integer(), nullable=False),
    sa.Column('dcreated_at', sa.DateTime(), nullable=True),
    sa.Column('vcreated_by', sa.String(length=100), nullable=True),
    sa.Column('dmodified_at', sa.DateTime(), nullable=True),
    sa.Column('vmodified_by', sa.String(length=100), nullable=True),
    sa.Column('dsort_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nid_booking'], ['tblt_booking.nid'], ),
    sa.ForeignKeyConstraint(['nid_file'], ['tblm_files.nid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_tblr_booking_files_vcode'), 'tblr_booking_files', ['vcode'], unique=True)
    op.create_index(op.f('ix_tblr_booking_files_vtype'), 'tblr_booking_files', ['vtype'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblr_booking_files_vtype'), table_name='tblr_booking_files')
    op.drop_index(op.f('ix_tblr_booking_files_vcode'), table_name='tblr_booking_files')
    op.drop_table('tblr_booking_files')
    op.drop_index(op.f('ix_tblt_booking_vcode'), table_name='tblt_booking')
    op.drop_index(op.f('ix_tblt_booking_nid'), table_name='tblt_booking')
    op.drop_table('tblt_booking')
    op.drop_index(op.f('ix_tblr_lab_content_files_vcode'), table_name='tblr_lab_content_files')
    op.drop_table('tblr_lab_content_files')
    op.drop_index(op.f('ix_tbls_landing_page_image_vcode'), table_name='tbls_landing_page_image')
    op.drop_table('tbls_landing_page_image')
    op.drop_index(op.f('ix_tblr_user_access_vcode'), table_name='tblr_user_access')
    op.drop_table('tblr_user_access')
    op.drop_index(op.f('ix_tblr_lab_gallery_vcode'), table_name='tblr_lab_gallery')
    op.drop_table('tblr_lab_gallery')
    op.drop_index(op.f('ix_tblr_lab_facility_vcode'), table_name='tblr_lab_facility')
    op.drop_table('tblr_lab_facility')
    op.drop_index(op.f('ix_tblr_lab_content_vcode'), table_name='tblr_lab_content')
    op.drop_table('tblr_lab_content')
    op.drop_index(op.f('ix_tblr_department_lab_vcode'), table_name='tblr_department_lab')
    op.drop_table('tblr_department_lab')
    op.drop_index(op.f('ix_tbls_token_vcode'), table_name='tbls_token')
    op.drop_index(op.f('ix_tbls_token_ntoken_type'), table_name='tbls_token')
    op.drop_table('tbls_token')
    op.drop_index(op.f('ix_tbls_landing_page_vcode'), table_name='tbls_landing_page')
    op.drop_table('tbls_landing_page')
    op.drop_index(op.f('ix_tblr_role_permissions_vcode'), table_name='tblr_role_permissions')
    op.drop_table('tblr_role_permissions')
    op.drop_index(op.f('ix_tblm_lab_vcode'), table_name='tblm_lab')
    op.drop_table('tblm_lab')
    op.drop_index(op.f('ix_tblm_facility_vcode'), table_name='tblm_facility')
    op.drop_table('tblm_facility')
    op.drop_index(op.f('ix_tblh_security_logs_vaction'), table_name='tblh_security_logs')
    op.drop_index(op.f('ix_tblh_security_logs_nid_user'), table_name='tblh_security_logs')
    op.drop_index(op.f('ix_tblh_security_logs_dtimestamp'), table_name='tblh_security_logs')
    op.drop_table('tblh_security_logs')
    op.drop_index(op.f('ix_tblh_activity_logs_vtarget_model'), table_name='tblh_activity_logs')
    op.drop_index(op.f('ix_tblh_activity_logs_vtarget_identifier'), table_name='tblh_activity_logs')
    op.drop_index(op.f('ix_tblh_activity_logs_vaction'), table_name='tblh_activity_logs')
    op.drop_index(op.f('ix_tblh_activity_logs_nid_user'), table_name='tblh_activity_logs')
    op.drop_index(op.f('ix_tblh_activity_logs_dtimestamp'), table_name='tblh_activity_logs')
    op.drop_table('tblh_activity_logs')
    op.drop_index(op.f('ix_tbls_users_vemail'), table_name='tbls_users')
    op.drop_index(op.f('ix_tbls_users_vcode'), table_name='tbls_users')
    op.drop_table('tbls_users')
    op.drop_index(op.f('ix_tblm_roles_vcode'), table_name='tblm_roles')
    op.drop_table('tblm_roles')
    op.drop_index(op.f('ix_tblm_permissions_vcode'), table_name='tblm_permissions')
    op.drop_table('tblm_permissions')
    op.drop_index(op.f('ix_tblm_files_vcode'), table_name='tblm_files')
    op.drop_table('tblm_files')
    op.drop_index(op.f('ix_tblm_department_vcode'), table_name='tblm_department')
    op.drop_table('tblm_department')
    op.drop_index(op.f('ix_tblm_building_vcode'), table_name='tblm_building')
    op.drop_table('tblm_building')
    # ### end Alembic commands ###
